feat: validate password criteria
reearth/reearth-backend pull request #116
Opened 2022-02-18 07:14 UTC by mimoham24

# Overview

## What I've done

## What I haven't done

## How I tested

## Which point I want you to review particularly

## Memo

2022-02-18 07:50 UTC, yk-eukarya commented on pkg/user/user.go
> +		case unicode.IsLetter(c) || c == ' ':
```suggestion
		case unicode.IsLower(c) || c == ' ':
```

2022-02-18 11:40 UTC, yk-eukarya approved these changes
LGTM

2022-02-18 11:56 UTC, rot1024 requested changes
Uppercase and lowercase concept of unicode are not limited to alphabet but other language characters. Is that expected?

- https://www.compart.com/en/unicode/category/Lu
- https://www.ibm.com/docs/en/i/7.2?topic=tables-unicode-lowercase-uppercase-conversion-mapping-table

2022-02-18 11:56 UTC, rot1024 commented on pkg/user/user.go
> +	}
```suggestion
	if err := validatePassword(pass); err != nil {
		return err
	}
```

2022-03-02 22:19 UTC, mimoham24 commented
@rot1024 after investigations it's ok to input a password with non-Latin characters 
the only concern is that it might cause encoding and decoding problems
so, after a meeting with @yk-eukarya we thought that having a test case with non-Latin characters will make sure that `crypto/bcrypt` can successfully encode and decode non-Latin passwords

2022-03-04 02:56 UTC, rot1024 commented
crypto/bcrypt should work. It is just a binary, so it doesn't matter at all what language the password is written in to bcrypt!

2022-03-04 03:03 UTC, rot1024 approved these changes

2022-03-04 07:36 UTC, merged