chore: use go:embed
reearth/reearth-backend pull request #24
Opened 2021-07-13 17:16 UTC by rot1024

# Overview

## What I've done

In golang v1.16, go embed is now available! tools/cmd/embed has been replaced by go:embed.

Currently JSON schema validator doesn't support YAML, so it is temporally disabled.

## What I haven't done

## How I tested

## Which point I want you to review particularly

## Memo

2021-07-21 07:08 UTC, KaWaite approved these changes

2021-07-29 06:09 UTC, mimoham24 approved these changes

2021-07-29 07:01 UTC, yk-eukarya requested changes

2021-07-30 06:07 UTC, rot1024 commented on pkg/plugin/manifest/parser.go
> +	_ "embed"
Import is needed, otherwise embed does not work。
Refer to https://pkg.go.dev/embed

2021-07-30 06:20 UTC, yk-eukarya commented on pkg/plugin/manifest/parser.go
> +	_ "embed"
//go:embed directive is not used in this file ```pkg/plugin/manifest/parser.go```, so no need for that import.
correct me if that is not correct.
also we have the same situation in the this file ```pkg/plugin/manifest/parser_translation.go```

2021-07-30 06:57 UTC, rot1024 commented on pkg/plugin/manifest/parser.go
> +	_ "embed"
Oh that's right. I will fix it.

2021-07-30 07:42 UTC, yk-eukarya approved these changes

2021-07-30 07:43 UTC, merged