feat: tag system domain models
reearth/reearth-backend pull request #39
Opened 2021-08-11 01:00 UTC by mimoham24

# Overview
tag system domain models
## What I've done
created the tag system domain models
## What I haven't done
create tag -> layer relationship
## How I tested
table-driven test units
## Which point I want you to review particularly
pkg/tag/...
pkg/id/gen.go
## Memo

2021-08-12 06:41 UTC, HideBa approved these changes
LGTM 👍

2021-08-23 09:16 UTC, rot1024 requested changes
Don't forget to check codecov's warnings about the existence of untested rows, and add more test cases.

2021-08-23 09:16 UTC, rot1024 commented on pkg/tag/item_test.go
> +			if err == nil {
```suggestion
			if tc.Expected.Error == nil {
```

If `tc.Expected.Error` is not nil but `err` is nil, there's a chance this test will pass.

2021-08-23 09:16 UTC, rot1024 commented on pkg/tag/item_test.go
> +				assert.True(tt, errors.As(tc.Expected.Error, &err))
```suggestion
				assert.Equal(tt, err, tc.Err)
```

Incorrect usage of `errors.As`. This assertion always passes.

Note: `testify/assert` has methods to assert errors: `assert.ErrorIs`, `assert.ErrorAs`

2021-08-23 09:16 UTC, rot1024 commented on pkg/tag/list.go
> +	return tl.tags
```suggestion
	return append([]id.Tags, tl.tags...)
```

Copying prevents the slice from being modified from outside the domain model.

2021-08-23 09:16 UTC, rot1024 commented on pkg/tag/list.go
> +	tl.tags = res
```suggestion
	for i := 0; i < len(tl.tags); i++ {
		for _, t := range tags {
			if tl.tags[i] == tid {
				tl.tags = append(tl.tags[:i], tl.tags[i+1:]...)
				i--
				break
			}
		}
	}
```

2021-08-23 09:19 UTC, rot1024 requested changes

2021-08-23 09:19 UTC, rot1024 commented on pkg/tag/item.go
> +	return i.linkedDatasetID
```suggestion
	return i.linkedDatasetID.CopyRef()
```

2021-08-23 09:19 UTC, rot1024 commented on pkg/tag/item.go
> +	return i.linkedDatasetFieldID
```suggestion
	return i.linkedDatasetFieldID.CopyRef()
```

2021-08-23 09:19 UTC, rot1024 commented on pkg/tag/item.go
> +	return i.linkedDatasetSchemaID
```suggestion
	return i.linkedDatasetSchemaID.CopyRef()
```

2021-08-24 03:15 UTC, rot1024 requested changes

2021-08-24 03:15 UTC, rot1024 commented on pkg/tag/tag.go
> +		return ti
Codecov warning: this line is not tested

2021-08-24 03:15 UTC, rot1024 commented on pkg/tag/tag.go
> +		return tg
Codecov warning: this line is not tested

2021-08-24 03:15 UTC, rot1024 commented on pkg/tag/list.go
> +		return
Codecov warning: this line is not tested

2021-08-24 03:15 UTC, rot1024 commented on pkg/tag/list.go
> +		return
Codecov warning: this line is not tested

2021-08-24 03:15 UTC, rot1024 commented on pkg/tag/list.go
> +		return false
Codecov warning: this line is not tested

2021-08-24 03:15 UTC, rot1024 commented on pkg/tag/item_test.go
> +	assert.NotNil(t, b.i.id)
```suggestion
	assert.NotEqual(t, id.TagID{}, b.i.id)
```

This assertion always passes because `b.i.id` is not a reference.

2021-08-24 17:06 UTC, rot1024 approved these changes

2021-08-24 17:07 UTC, merged