Feat/mutation to create tag
reearth/reearth-backend pull request #45
Opened 2021-09-10 07:47 UTC by mimoham24

# Overview
`createTagItem` and `createTagGroup` mutations 
## What I've done
- create graphQL schema
- create the presentation layer
- create dummy infrastructure/memory layer (will create another PR implementing it)
- create use-case layer
- implement creating tag items and groups mutations

## What I haven't done
implementing `infrastructure/memory`
## How I tested
providing dummy data to the mutations
## Which point I want you to review particularly

## Memo

2021-09-13 03:36 UTC, HideBa approved these changes
LGTM

2021-09-14 09:18 UTC, rot1024 requested changes

2021-09-14 09:18 UTC, rot1024 commented on internal/usecase/interactor/tag.go
> +	if err := i.CanReadScene(ctx, inp.SceneID, operator); err != nil {
```suggestion
	if err := i.CanWriteScene(ctx, inp.SceneID, operator); err != nil {
```

2021-09-14 09:18 UTC, rot1024 commented on internal/usecase/interactor/tag.go
> +	if err := i.CanReadScene(ctx, inp.SceneID, operator); err != nil {
```suggestion
	if err := i.CanWriteScene(ctx, inp.SceneID, operator); err != nil {
```

2021-09-14 09:18 UTC, rot1024 commented on schema.graphql
> +  tags: [ID]
```suggestion
  tags: [ID!]!
```

2021-09-14 09:18 UTC, rot1024 commented on schema.graphql
> +  tags: [ID]
```suggestion
  tags: [ID!]!
```

2021-09-14 09:18 UTC, rot1024 commented on schema.graphql
> +  label: String!
```suggestion
  label: String
```

When the user does not want to update the name, the user won't set the label field

2021-09-15 08:09 UTC, rot1024 commented on schema.graphql
> +  label: String!
Note: apply this suggestion only for UpdateTag*Input

2021-09-15 09:27 UTC, rot1024 approved these changes

2021-09-15 12:05 UTC, merged