- send mail
reearth/reearth-backend pull request #86
Opened 2021-12-02 07:34 UTC by yk-eukarya

2021-12-02 13:54 UTC, mimoham24 requested changes

2021-12-02 13:54 UTC, mimoham24 commented on internal/usecase/interactor/emails/password_reset_html.tmpl
> +
no need for those lines as content-type is generated by `SendMail()`
```suggestion
```

2021-12-02 13:54 UTC, mimoham24 commented on internal/usecase/interactor/emails/password_reset_text.tmpl
> +Mime-Version: 1.0
same here
```suggestion

```

2021-12-06 06:43 UTC, rot1024 requested changes

2021-12-06 06:43 UTC, rot1024 commented on internal/usecase/interactor/user.go
> +	t1, err := textTmpl.New("passwordReset").Parse(passwordResetTextTMPL)
Make parsing templates in init() and put result in package variable. Another email template should be changed also.

```go
var emailTemplate *text.Template // Be careful of the variable name as it is a package variable

func init() {
	emailTemplate, err := textTmpl.New("passwordReset").Parse(passwordResetTextTMPL)
	if err != nil {
		log.Panicf("password reset email template parse error: %s", err)
	}
}
```

2021-12-06 09:27 UTC, rot1024 approved these changes

2021-12-06 09:27 UTC, rot1024 commented on internal/usecase/interactor/user.go
> +		log.Panicf("password reset email template parse error: %s", err)
```suggestion
		log.Panicf("password reset email template parse error: %s\n", err)
```

2021-12-06 09:27 UTC, rot1024 commented on internal/usecase/interactor/user.go
> +		log.Panicf("password reset email template parse error: %s", err)
```suggestion
		log.Panicf("password reset email template parse error: %s\n", err)
```

2021-12-06 12:52 UTC, mimoham24 approved these changes

2021-12-06 13:46 UTC, merged